/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2018-02-28 06:27:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pdfview.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("Copyright 2012 Mozilla Foundation\n");
      out.write("\n");
      out.write("Licensed under the Apache License, Version 2.0 (the \"License\");\n");
      out.write("you may not use this file except in compliance with the License.\n");
      out.write("You may obtain a copy of the License at\n");
      out.write("\n");
      out.write("    http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write("\n");
      out.write("Unless required by applicable law or agreed to in writing, software\n");
      out.write("distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("See the License for the specific language governing permissions and\n");
      out.write("limitations under the License.\n");
      out.write("\n");
      out.write("Adobe CMap resources are covered by their own copyright but the same license:\n");
      out.write("\n");
      out.write("    Copyright 1990-2015 Adobe Systems Incorporated.\n");
      out.write("\n");
      out.write("See https://github.com/adobe-type-tools/cmap-resources\n");
      out.write("-->\n");
      out.write("<html dir=\"ltr\" mozdisallowselectionprint moznomarginboxes>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("    <meta name=\"google\" content=\"notranslate\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <title>PDF.js viewer</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"viewer.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- This snippet is used in production (included from viewer.html) -->\n");
      out.write("<link rel=\"resource\" type=\"application/l10n\" href=\"locale/locale.properties\">\n");
      out.write("<script src=\"../build/pdf.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"viewer.js\"></script>\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body tabindex=\"1\" class=\"loadingInProgress\">\n");
      out.write("    <div id=\"outerContainer\">\n");
      out.write("\n");
      out.write("      <div id=\"sidebarContainer\">\n");
      out.write("        <div id=\"toolbarSidebar\">\n");
      out.write("          <div class=\"splitToolbarButton toggled\">\n");
      out.write("            <button id=\"viewThumbnail\" class=\"toolbarButton toggled\" title=\"Show Thumbnails\" tabindex=\"2\" data-l10n-id=\"thumbs\">\n");
      out.write("               <span data-l10n-id=\"thumbs_label\">Thumbnails</span>\n");
      out.write("            </button>\n");
      out.write("            <button id=\"viewOutline\" class=\"toolbarButton\" title=\"Show Document Outline (double-click to expand/collapse all items)\" tabindex=\"3\" data-l10n-id=\"document_outline\">\n");
      out.write("               <span data-l10n-id=\"document_outline_label\">Document Outline</span>\n");
      out.write("            </button>\n");
      out.write("            <button id=\"viewAttachments\" class=\"toolbarButton\" title=\"Show Attachments\" tabindex=\"4\" data-l10n-id=\"attachments\">\n");
      out.write("               <span data-l10n-id=\"attachments_label\">Attachments</span>\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"sidebarContent\">\n");
      out.write("          <div id=\"thumbnailView\">\n");
      out.write("          </div>\n");
      out.write("          <div id=\"outlineView\" class=\"hidden\">\n");
      out.write("          </div>\n");
      out.write("          <div id=\"attachmentsView\" class=\"hidden\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>  <!-- sidebarContainer -->\n");
      out.write("\n");
      out.write("      <div id=\"mainContainer\">\n");
      out.write("        <div class=\"findbar hidden doorHanger\" id=\"findbar\">\n");
      out.write("          <div id=\"findbarInputContainer\">\n");
      out.write("            <input id=\"findInput\" class=\"toolbarField\" title=\"Find\" placeholder=\"Find in document…\" tabindex=\"91\" data-l10n-id=\"find_input\">\n");
      out.write("            <div class=\"splitToolbarButton\">\n");
      out.write("              <button id=\"findPrevious\" class=\"toolbarButton findPrevious\" title=\"Find the previous occurrence of the phrase\" tabindex=\"92\" data-l10n-id=\"find_previous\">\n");
      out.write("                <span data-l10n-id=\"find_previous_label\">Previous</span>\n");
      out.write("              </button>\n");
      out.write("              <div class=\"splitToolbarButtonSeparator\"></div>\n");
      out.write("              <button id=\"findNext\" class=\"toolbarButton findNext\" title=\"Find the next occurrence of the phrase\" tabindex=\"93\" data-l10n-id=\"find_next\">\n");
      out.write("                <span data-l10n-id=\"find_next_label\">Next</span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div id=\"findbarOptionsContainer\">\n");
      out.write("            <input type=\"checkbox\" id=\"findHighlightAll\" class=\"toolbarField\" tabindex=\"94\">\n");
      out.write("            <label for=\"findHighlightAll\" class=\"toolbarLabel\" data-l10n-id=\"find_highlight\">Highlight all</label>\n");
      out.write("            <input type=\"checkbox\" id=\"findMatchCase\" class=\"toolbarField\" tabindex=\"95\">\n");
      out.write("            <label for=\"findMatchCase\" class=\"toolbarLabel\" data-l10n-id=\"find_match_case_label\">Match case</label>\n");
      out.write("            <span id=\"findResultsCount\" class=\"toolbarLabel hidden\"></span>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div id=\"findbarMessageContainer\">\n");
      out.write("            <span id=\"findMsg\" class=\"toolbarLabel\"></span>\n");
      out.write("          </div>\n");
      out.write("        </div>  <!-- findbar -->\n");
      out.write("\n");
      out.write("        <div id=\"secondaryToolbar\" class=\"secondaryToolbar hidden doorHangerRight\">\n");
      out.write("          <div id=\"secondaryToolbarButtonContainer\">\n");
      out.write("            <button id=\"secondaryPresentationMode\" class=\"secondaryToolbarButton presentationMode visibleLargeView\" title=\"Switch to Presentation Mode\" tabindex=\"51\" data-l10n-id=\"presentation_mode\">\n");
      out.write("              <span data-l10n-id=\"presentation_mode_label\">Presentation Mode</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <button id=\"secondaryOpenFile\" class=\"secondaryToolbarButton openFile visibleLargeView\" title=\"Open File\" tabindex=\"52\" data-l10n-id=\"open_file\">\n");
      out.write("              <span data-l10n-id=\"open_file_label\">Open</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <button id=\"secondaryPrint\" class=\"secondaryToolbarButton print visibleMediumView\" title=\"Print\" tabindex=\"53\" data-l10n-id=\"print\">\n");
      out.write("              <span data-l10n-id=\"print_label\">Print</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <button id=\"secondaryDownload\" class=\"secondaryToolbarButton download visibleMediumView\" title=\"Download\" tabindex=\"54\" data-l10n-id=\"download\">\n");
      out.write("              <span data-l10n-id=\"download_label\">Download</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <a href=\"#\" id=\"secondaryViewBookmark\" class=\"secondaryToolbarButton bookmark visibleSmallView\" title=\"Current view (copy or open in new window)\" tabindex=\"55\" data-l10n-id=\"bookmark\">\n");
      out.write("              <span data-l10n-id=\"bookmark_label\">Current View</span>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <div class=\"horizontalToolbarSeparator visibleLargeView\"></div>\n");
      out.write("\n");
      out.write("            <button id=\"firstPage\" class=\"secondaryToolbarButton firstPage\" title=\"Go to First Page\" tabindex=\"56\" data-l10n-id=\"first_page\">\n");
      out.write("              <span data-l10n-id=\"first_page_label\">Go to First Page</span>\n");
      out.write("            </button>\n");
      out.write("            <button id=\"lastPage\" class=\"secondaryToolbarButton lastPage\" title=\"Go to Last Page\" tabindex=\"57\" data-l10n-id=\"last_page\">\n");
      out.write("              <span data-l10n-id=\"last_page_label\">Go to Last Page</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"horizontalToolbarSeparator\"></div>\n");
      out.write("\n");
      out.write("            <button id=\"pageRotateCw\" class=\"secondaryToolbarButton rotateCw\" title=\"Rotate Clockwise\" tabindex=\"58\" data-l10n-id=\"page_rotate_cw\">\n");
      out.write("              <span data-l10n-id=\"page_rotate_cw_label\">Rotate Clockwise</span>\n");
      out.write("            </button>\n");
      out.write("            <button id=\"pageRotateCcw\" class=\"secondaryToolbarButton rotateCcw\" title=\"Rotate Counterclockwise\" tabindex=\"59\" data-l10n-id=\"page_rotate_ccw\">\n");
      out.write("              <span data-l10n-id=\"page_rotate_ccw_label\">Rotate Counterclockwise</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"horizontalToolbarSeparator\"></div>\n");
      out.write("\n");
      out.write("            <button id=\"cursorSelectTool\" class=\"secondaryToolbarButton selectTool toggled\" title=\"Enable Text Selection Tool\" tabindex=\"60\" data-l10n-id=\"cursor_text_select_tool\">\n");
      out.write("              <span data-l10n-id=\"cursor_text_select_tool_label\">Text Selection Tool</span>\n");
      out.write("            </button>\n");
      out.write("            <button id=\"cursorHandTool\" class=\"secondaryToolbarButton handTool\" title=\"Enable Hand Tool\" tabindex=\"61\" data-l10n-id=\"cursor_hand_tool\">\n");
      out.write("              <span data-l10n-id=\"cursor_hand_tool_label\">Hand Tool</span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div class=\"horizontalToolbarSeparator\"></div>\n");
      out.write("\n");
      out.write("            <button id=\"documentProperties\" class=\"secondaryToolbarButton documentProperties\" title=\"Document Properties…\" tabindex=\"62\" data-l10n-id=\"document_properties\">\n");
      out.write("              <span data-l10n-id=\"document_properties_label\">Document Properties…</span>\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("        </div>  <!-- secondaryToolbar -->\n");
      out.write("\n");
      out.write("        <div class=\"toolbar\">\n");
      out.write("          <div id=\"toolbarContainer\">\n");
      out.write("            <div id=\"toolbarViewer\">\n");
      out.write("              <div id=\"toolbarViewerLeft\">\n");
      out.write("                <button id=\"sidebarToggle\" class=\"toolbarButton\" title=\"Toggle Sidebar\" tabindex=\"11\" data-l10n-id=\"toggle_sidebar\">\n");
      out.write("                  <span data-l10n-id=\"toggle_sidebar_label\">Toggle Sidebar</span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"toolbarButtonSpacer\"></div>\n");
      out.write("                <button id=\"viewFind\" class=\"toolbarButton\" title=\"Find in Document\" tabindex=\"12\" data-l10n-id=\"findbar\">\n");
      out.write("                  <span data-l10n-id=\"findbar_label\">Find</span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"splitToolbarButton hiddenSmallView\">\n");
      out.write("                  <button class=\"toolbarButton pageUp\" title=\"Previous Page\" id=\"previous\" tabindex=\"13\" data-l10n-id=\"previous\">\n");
      out.write("                    <span data-l10n-id=\"previous_label\">Previous</span>\n");
      out.write("                  </button>\n");
      out.write("                  <div class=\"splitToolbarButtonSeparator\"></div>\n");
      out.write("                  <button class=\"toolbarButton pageDown\" title=\"Next Page\" id=\"next\" tabindex=\"14\" data-l10n-id=\"next\">\n");
      out.write("                    <span data-l10n-id=\"next_label\">Next</span>\n");
      out.write("                  </button>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"number\" id=\"pageNumber\" class=\"toolbarField pageNumber\" title=\"Page\" value=\"1\" size=\"4\" min=\"1\" tabindex=\"15\" data-l10n-id=\"page\">\n");
      out.write("                <span id=\"numPages\" class=\"toolbarLabel\"></span>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"toolbarViewerRight\">\n");
      out.write("                <button id=\"presentationMode\" class=\"toolbarButton presentationMode hiddenLargeView\" title=\"Switch to Presentation Mode\" tabindex=\"31\" data-l10n-id=\"presentation_mode\">\n");
      out.write("                  <span data-l10n-id=\"presentation_mode_label\">Presentation Mode</span>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button id=\"openFile\" class=\"toolbarButton openFile hiddenLargeView\" title=\"Open File\" tabindex=\"32\" data-l10n-id=\"open_file\" style=\"display: none\">\n");
      out.write("                  <span data-l10n-id=\"open_file_label\">Open</span>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button id=\"print\" class=\"toolbarButton print hiddenMediumView\" title=\"Print\" tabindex=\"33\" data-l10n-id=\"print\" style=\"display: none\">\n");
      out.write("                  <span data-l10n-id=\"print_label\">Print</span>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("                <button id=\"download\" class=\"toolbarButton download hiddenMediumView\" title=\"Download\" tabindex=\"34\" data-l10n-id=\"download\" style=\"display: none\">\n");
      out.write("                  <span data-l10n-id=\"download_label\">Download</span>\n");
      out.write("                </button>\n");
      out.write("                <a href=\"#\" id=\"viewBookmark\" class=\"toolbarButton bookmark hiddenSmallView\" title=\"Current view (copy or open in new window)\" tabindex=\"35\" data-l10n-id=\"bookmark\">\n");
      out.write("                  <span data-l10n-id=\"bookmark_label\">Current View</span>\n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <div class=\"verticalToolbarSeparator hiddenSmallView\"></div>\n");
      out.write("\n");
      out.write("                <button id=\"secondaryToolbarToggle\" class=\"toolbarButton\" title=\"Tools\" tabindex=\"36\" data-l10n-id=\"tools\">\n");
      out.write("                  <span data-l10n-id=\"tools_label\">Tools</span>\n");
      out.write("                </button>\n");
      out.write("              </div>\n");
      out.write("              <div id=\"toolbarViewerMiddle\">\n");
      out.write("                <div class=\"splitToolbarButton\">\n");
      out.write("                  <button id=\"zoomOut\" class=\"toolbarButton zoomOut\" title=\"Zoom Out\" tabindex=\"21\" data-l10n-id=\"zoom_out\">\n");
      out.write("                    <span data-l10n-id=\"zoom_out_label\">Zoom Out</span>\n");
      out.write("                  </button>\n");
      out.write("                  <div class=\"splitToolbarButtonSeparator\"></div>\n");
      out.write("                  <button id=\"zoomIn\" class=\"toolbarButton zoomIn\" title=\"Zoom In\" tabindex=\"22\" data-l10n-id=\"zoom_in\">\n");
      out.write("                    <span data-l10n-id=\"zoom_in_label\">Zoom In</span>\n");
      out.write("                   </button>\n");
      out.write("                </div>\n");
      out.write("                <span id=\"scaleSelectContainer\" class=\"dropdownToolbarButton\">\n");
      out.write("                  <select id=\"scaleSelect\" title=\"Zoom\" tabindex=\"23\" data-l10n-id=\"zoom\">\n");
      out.write("                    <option id=\"pageAutoOption\" title=\"\" value=\"auto\" selected=\"selected\" data-l10n-id=\"page_scale_auto\">Automatic Zoom</option>\n");
      out.write("                    <option id=\"pageActualOption\" title=\"\" value=\"page-actual\" data-l10n-id=\"page_scale_actual\">Actual Size</option>\n");
      out.write("                    <option id=\"pageFitOption\" title=\"\" value=\"page-fit\" data-l10n-id=\"page_scale_fit\">Page Fit</option>\n");
      out.write("                    <option id=\"pageWidthOption\" title=\"\" value=\"page-width\" data-l10n-id=\"page_scale_width\">Page Width</option>\n");
      out.write("                    <option id=\"customScaleOption\" title=\"\" value=\"custom\" disabled=\"disabled\" hidden=\"true\"></option>\n");
      out.write("                    <option title=\"\" value=\"0.5\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 50 }'>50%</option>\n");
      out.write("                    <option title=\"\" value=\"0.75\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 75 }'>75%</option>\n");
      out.write("                    <option title=\"\" value=\"1\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 100 }'>100%</option>\n");
      out.write("                    <option title=\"\" value=\"1.25\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 125 }'>125%</option>\n");
      out.write("                    <option title=\"\" value=\"1.5\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 150 }'>150%</option>\n");
      out.write("                    <option title=\"\" value=\"2\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 200 }'>200%</option>\n");
      out.write("                    <option title=\"\" value=\"3\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 300 }'>300%</option>\n");
      out.write("                    <option title=\"\" value=\"4\" data-l10n-id=\"page_scale_percent\" data-l10n-args='{ \"scale\": 400 }'>400%</option>\n");
      out.write("                  </select>\n");
      out.write("                </span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"loadingBar\">\n");
      out.write("              <div class=\"progress\">\n");
      out.write("                <div class=\"glimmer\">\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <menu type=\"context\" id=\"viewerContextMenu\">\n");
      out.write("          <menuitem id=\"contextFirstPage\" label=\"First Page\"\n");
      out.write("                    data-l10n-id=\"first_page\"></menuitem>\n");
      out.write("          <menuitem id=\"contextLastPage\" label=\"Last Page\"\n");
      out.write("                    data-l10n-id=\"last_page\"></menuitem>\n");
      out.write("          <menuitem id=\"contextPageRotateCw\" label=\"Rotate Clockwise\"\n");
      out.write("                    data-l10n-id=\"page_rotate_cw\"></menuitem>\n");
      out.write("          <menuitem id=\"contextPageRotateCcw\" label=\"Rotate Counter-Clockwise\"\n");
      out.write("                    data-l10n-id=\"page_rotate_ccw\"></menuitem>\n");
      out.write("        </menu>\n");
      out.write("\n");
      out.write("        <div id=\"viewerContainer\" tabindex=\"0\">\n");
      out.write("          <div id=\"viewer\" class=\"pdfViewer\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"errorWrapper\" hidden='true'>\n");
      out.write("          <div id=\"errorMessageLeft\">\n");
      out.write("            <span id=\"errorMessage\"></span>\n");
      out.write("            <button id=\"errorShowMore\" data-l10n-id=\"error_more_info\">\n");
      out.write("              More Information\n");
      out.write("            </button>\n");
      out.write("            <button id=\"errorShowLess\" data-l10n-id=\"error_less_info\" hidden='true'>\n");
      out.write("              Less Information\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("          <div id=\"errorMessageRight\">\n");
      out.write("            <button id=\"errorClose\" data-l10n-id=\"error_close\">\n");
      out.write("              Close\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"clearBoth\"></div>\n");
      out.write("          <textarea id=\"errorMoreInfo\" hidden='true' readonly=\"readonly\"></textarea>\n");
      out.write("        </div>\n");
      out.write("      </div> <!-- mainContainer -->\n");
      out.write("\n");
      out.write("      <div id=\"overlayContainer\" class=\"hidden\">\n");
      out.write("        <div id=\"passwordOverlay\" class=\"container hidden\">\n");
      out.write("          <div class=\"dialog\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <p id=\"passwordText\" data-l10n-id=\"password_label\">Enter the password to open this PDF file:</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <input type=\"password\" id=\"password\" class=\"toolbarField\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"buttonRow\">\n");
      out.write("              <button id=\"passwordCancel\" class=\"overlayButton\"><span data-l10n-id=\"password_cancel\">Cancel</span></button>\n");
      out.write("              <button id=\"passwordSubmit\" class=\"overlayButton\"><span data-l10n-id=\"password_ok\">OK</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"documentPropertiesOverlay\" class=\"container hidden\">\n");
      out.write("          <div class=\"dialog\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_file_name\">File name:</span> <p id=\"fileNameField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_file_size\">File size:</span> <p id=\"fileSizeField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"separator\"></div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_title\">Title:</span> <p id=\"titleField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_author\">Author:</span> <p id=\"authorField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_subject\">Subject:</span> <p id=\"subjectField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_keywords\">Keywords:</span> <p id=\"keywordsField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_creation_date\">Creation Date:</span> <p id=\"creationDateField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_modification_date\">Modification Date:</span> <p id=\"modificationDateField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_creator\">Creator:</span> <p id=\"creatorField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"separator\"></div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_producer\">PDF Producer:</span> <p id=\"producerField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_version\">PDF Version:</span> <p id=\"versionField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"document_properties_page_count\">Page Count:</span> <p id=\"pageCountField\">-</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"buttonRow\">\n");
      out.write("              <button id=\"documentPropertiesClose\" class=\"overlayButton\"><span data-l10n-id=\"document_properties_close\">Close</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"printServiceOverlay\" class=\"container hidden\">\n");
      out.write("          <div class=\"dialog\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <span data-l10n-id=\"print_progress_message\">Preparing document for printing…</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <progress value=\"0\" max=\"100\"></progress>\n");
      out.write("              <span data-l10n-id=\"print_progress_percent\" data-l10n-args='{ \"progress\": 0 }' class=\"relative-progress\">0%</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"buttonRow\">\n");
      out.write("              <button id=\"printCancel\" class=\"overlayButton\"><span data-l10n-id=\"print_progress_close\">Cancel</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>  <!-- overlayContainer -->\n");
      out.write("\n");
      out.write("    </div> <!-- outerContainer -->\n");
      out.write("    <div id=\"printContainer\"></div>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
